---
- name: remove dns entries for each vs code instance
  include_tasks: teardown.yml
  when: teardown|bool

- name: check to see if SSL cert already applied
  become: false
  get_certificate:
    host: "{{username}}-code.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    port: 443
  delegate_to: localhost
  run_once: true
  register: check_cert
  ignore_errors: true
  failed_when: false
  when:
    - not teardown

- name: perform DNS and SSL certs for ansible control node
  block:
    - name: setup vscode for web browser access
      include_tasks: "codeserver.yml"
  when:
    - not teardown|bool
    - check_cert.cert is not defined
