---
- name: Teardown attendance
  include_tasks: teardown.yml
  when: teardown|bool

- name: Add route 53 record
  import_tasks: dns.yml
  when: not teardown

- name: Debug cluster subdomain
  debug:
    msg: "OpenShift Cluster subdomain is {{ openshift_cluster_subdomain }}"
  when:
    - (openshift_install is defined) and (openshift_install | bool) 

- name: Configure attendance host
  import_tasks: attendance.yml
  when: not teardown

- name: set information for instructor
  set_fact:
    login_website_information: "Auto-Assignment website located at http://{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone|lower }}, instructor can see workbench assignments at http://{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone|lower }}/list.php"
  delegate_to: localhost
  run_once: true
