---
- name: remove dns entries for each tower node
  include_tasks: teardown.yml
  when: teardown|bool

- name: check to see if SSL cert already applied
  uri:
    url: "https://{{username}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}/api/v2/ping/"
    method: GET
    user: admin
    password: "{{admin_password}}"
    validate_certs: true
    force_basic_auth: true
  register: check_cert
  ignore_errors: true
  failed_when: false
  when:
    - not teardown

