---
# https://docs.ansible.com/ansible-tower/latest/html/administration/init_script.html
- name: make sure Ansible Tower is online before changing tower base URL
  service:
    name: ansible-tower.service
    state: started
  register: start_tower
  until: start_tower is not failed
  retries: 5

- name: install certbot if not already installed
  dnf:
    name: certbot
    state: present
    disable_gpg_check: true

- name: change ansible tower base URL
  awx.awx.tower_settings:
    name: TOWER_URL_BASE
    value: "https://{{ username }}.{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}"
    tower_verify_ssl: false
    tower_host: localhost
    tower_username: admin
    tower_password: "{{ admin_password }}"
  register: change_base_url
  until: change_base_url is not failed
  retries: 5

# https://docs.ansible.com/ansible-tower/latest/html/administration/init_script.html
- name: make sure Ansible Tower is stopped
  service:
    name: ansible-tower.service
    state: stopped
  register: stop_tower
  until: stop_tower is not failed
  retries: 5

- name: SSL cert block
  block:
    # If this fails check out status of certbot: https://letsencrypt.status.io/
    - name: ISSUE CERT
      shell: certbot certonly --no-bootstrap --standalone -d {{username}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}} --email ansible-network@redhat.com --noninteractive --agree-tos
      register: issue_cert
      until: issue_cert is not failed
      retries: 5

    - name: MOVE SSL KEY
      copy:
        remote_src: true
        src: "/etc/letsencrypt/live/{{username}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}/privkey.pem"
        dest: /etc/tower/tower.key

    - name: GRAB SPECIFIC SSL CERT
      slurp:
        src: "/etc/letsencrypt/live/{{username}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}/cert.pem"
      register: intermediate_cert

    - name: COMBINE SPECIFIC AND INTERMEDIATE CERT
      template:
        src: combined_cert.j2
        dest: /etc/tower/tower.cert
  rescue:
    - name: make sure Ansible Tower is started
      service:
        name: ansible-tower.service
        state: started
      register: start_tower
      until: start_tower is not failed
      retries: 5

    - name: no SSL cert for Ansible Tower
      debug:
        msg: "SSL cert problem - no cert applied"
