---
- block:
  - name: Download Microsoft Visual C++ Redistributable Packages needed for SmartConsole
    win_chocolatey:
      name:
        - vcredist2010
        - vcredist2012
      state: present

  - name: Set strong cryptography on 64 bit .Net Framework (version 4 and above)
    win_shell: >
      Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

  - name: Set strong cryptography on 32 bit .Net Framework (version 4 and above)
    win_shell: >
      Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

  - name: Ensure the required NuGet package provider version is installed
    win_shell: Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force

  - name: Install Pscx needed for unzip step later
    win_psmodule:
      name: pscx
      allow_clobber: true

  - name: Check if SmartConsole is downloaded
    win_stat:
      path: C:\Temp\SmartConsole.exe
    register: smartconsole

  - name: Download SmartConsole to specified path only if modified
    win_get_url:
      url: https://s3.amazonaws.com/linklight.securityautomation/Check_Point_SmartConsole_R80_40_jumbo_HF_B416_Win.exe
      dest: C:\Temp\SmartConsole.exe
      checksum: c8bed1481f168e2af6997dc7d5b43ce4046e01d8
      force: true
    when: not smartconsole.stat.exists
    register: win_get_smartconsole
    until: win_get_smartconsole is success
    retries: 5

  - name: Unpack SmartConsole archive
    win_unzip:
      src: C:\Temp\SmartConsole.exe
      dest: C:\Temp\SmartConsole
      creates: C:\Temp\SmartConsole\SmartConsole.exe

  - name: Copy installer answer file to appropriate place
    win_copy:
      src: setup.iss
      dest: C:\Temp\SmartConsole\setup.iss

  - name: Execute SmartConsole installer
    win_command: C:\Temp\SmartConsole\SmartConsole.exe -s setup.iss
