---
- name: Destroy lab instances in AWS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  vars:
    ec2_wait: false
    teardown: true
    s3_state: absent
    state: absent
    debug_teardown: false

  tasks:
    - {include_role: {name: manage_ec2_instances}}
    - {include_role: {name: aws_dns}, when: dns_type == "aws"}
    - {include_role: {name: code_server}, when: code_server}
    - {include_role: {name: gitlab-server}, when: workshop_type == "windows"}
    - {include_role: {name: workshop_attendance}, when: attendance}


    - name: Remove workshop local files
      file:
        dest: "{{ playbook_dir }}/{{ ec2_name_prefix }}"
        state: absent
